### ISSUE TITLE
Some Text Changes

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#20]
If we could change the following:

When assigning paper vouchers (not qr code vouchers), could the button text say 'Assign' rather than 'Confirm'.
And to undo this change, click on 'Undo Assignment' rather than 'Revert'.
'Enter name' text should be 'Search Names'.
On popup 'Current Data' should be 'Latest Update'.

**Comment by vaclavlegat** [comment]
Text changes will be included in the next release.

**Comment by vaclavlegat** [comment]
Fixed in version 1.1.0
