### ISSUE TITLE
Clarifying 'ID Numbers' in App

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#23]
In ‘Household’ targeted distributions, Humansis ID should be the Household ID and the ID should be their National ID card number. See attached screens for what I mean.

![screen1](https://user-images.githubusercontent.com/31128624/67840509-57982b80-faf6-11e9-91a9-d9b9ff08398c.jpg)
![screen2](https://user-images.githubusercontent.com/31128624/67840515-5a931c00-faf6-11e9-9337-9378593cb985.jpg)

**Comment by PetrKubes97** [comment]
Imlemented.
