### ISSUE TITLE
User Permissions from Web Application

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#25]
User permissions from web application need to apply. For example only Syria staff should be able to access Syria projects.

**Comment by PetrKubes97** [comment]
I am not sure how should we go about implementing this. I think backend should not be providing other projects to Syrian staff in the first place.

**Comment by Happs80** [comment]
The back end prevents access, but the menu option is still there.

I get a 403 forbidden if i try to access a different country.

Not a huge issue, but would be good to remove the choice if possible.

**Comment by PetrKubes97** [comment]
<img width="1670" alt="Screenshot 2019-11-06 at 18 41 29" src="https://user-images.githubusercontent.com/4227953/68323277-6ddd5300-00c5-11ea-93ba-971157eb0f92.png">
Is there some endpoint to get a list of countries form?  Currently we are getting none from the login endpoint, so we just hardcoded KHM and SYR in the app.

**Comment by Happs80** [comment]
let me check with the web devs and come back to you.

**Comment by simon-krucinin-applifting** [comment]
I don't think this is currently possible. The country identifiers are hardcoded in client, so we don't know in advance which regions are permitted.

**Comment by Happs80** [comment]
Seems to be working (well at least it kicks you out and you have to log back in to your country again).
