### ISSUE TITLE
Number of Households Wrong on Dist Display

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#26]
![Screenshot_20191111-114848](https://user-images.githubusercontent.com/31128624/68581862-9c6a7d80-0479-11ea-8cbb-5fa9dc1f9647.jpg)

![Screenshot_20191111-115147](https://user-images.githubusercontent.com/31128624/68581879-aab89980-0479-11ea-95ae-b87821e82e65.jpg)

**Comment by simon-krucinin-applifting** [comment]
@Happs80 Well, the project takes into account all distributions in it (probably even those not currently active). Are you saying we should try to display only the number based on the downloaded distributions within the project?

Just trying to clarify the report. What is the issue and what is the expected result.

**Comment by Happs80** [comment]
Ah I see. My misunderstanding..

Thanks.
