### ISSUE TITLE
Strange behavior of sorting button

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#32]
From the specification:
3 state button is actually wanted:
 1. Grouped, sorted A-Z: the default state.
 2. Sorted A-Z without grouping (button active).
 3. Sorted Z-A without grouping (button active).

Yet currently it has only 2 states and:
* AZ seems to sort descending (!) by family name
* ZA seems to sort ascending (!) by family name
* There's no way to return to grouped (by distributed status first) sorting.
* The name displayed is "first name family name", so the sorting just by family name is utterly confusing.

**Comment by simon-krucinin-applifting** [comment]
There are still issues:
1. Grouped state should be the default. (Undistributed items first.)
2. After search (without touching the sorting button) the sort seems to behave differently. (Grouped search, while the button shows something else?)

**Comment by vaclavlegat** [comment]
1. Default sort set to `Grouped`
2. Search results are sorted according to currently selected sort type.
