### ISSUE TITLE
Reporting errors to user

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#41]
We should report more user-friendly error messages to users during data synchronization. I propose the following messages to appear in toast and sync dialog based on the first error that occurred. The full report (error type, response body, description, etc.) for each error should go to the developer log in settings.

Messages to user:
* Network error: 
  * If no connection: “Network connection lost.”
  * Other: “There was a network error.”
* HTTP errors: “Server responded with error <error code>.” Second line:
  * 400: “Bad request.”
  * 403: “User not allowed.”
  * 404: “Resource not found.”
  * 409: “There was a data conflict.”
  * 410: “Server API changed.”
  * 429: “Too many requests."
  * `>=500: “Server failure."`
* Parsing response errors: “Response format not recognized."
* Other: “An unexpected error occurred."

**Comment by vaclavlegat** [comment]
Added user friendly error messages, only the first error is displayed in toast.
