### ISSUE TITLE
Wrong projects after switching regions

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#43]
When offline, switching to another region produces an error, but the toggle changes successfully -- so for example, I have SYR projects loaded, I switch to KHM from settings, an error flashes briefly, but the selector says KHM now, I go to Projects and see projects from SYR (which is confusing already). Furthermore, I can't refresh KHM again from settings; it won't let me reselect the same item. I have to switch to another region and then switch back after turning on my connection. (Running manual data sync is not obvious is this scenario.)

On error, the state should revert back to the state before error.

**Comment by vaclavlegat** [comment]
Country selection is now disabled if there is no connection.

**Comment by simon-krucinin-applifting** [comment]
Well, it still doesn't work when I switch and then turn off the wi-fi (network fails, for example).

**Comment by PetrKubes97** [comment]
Is it sufficient clear all data when the switch begins so that there aren't any old data left when sync fails?

**Comment by simon-krucinin-applifting** [comment]
It's a good start. I would also like some indication that the data is incomplete if the first sync after switching fails.

**Comment by vaclavlegat** [comment]
I added icon next to status icon. It is displayed when `Last update failed` text is displayed in sync dialog, so when last failed date is persisted.
![device-2019-12-12-170357](https://user-images.githubusercontent.com/30039191/70728393-9e865d00-1d01-11ea-887c-bcc7856d8c09.png)
