### ISSUE TITLE
Assignment screen and detail are missing title

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#49]
There should be title for distributed item detail and assignment. It looks weirdly incomplete without it.

**Comment by simon-krucinin-applifting** [comment]
Well, it's even worse now.

1. It says "Assign Booklet" for everything. Let's just keep it "Assign" when not distributed and "Detail" when distributed.
2. Title overlaps with button (see "Undo assignment", for example). Really? Can we truncate the texts to the space available, please?

**Comment by vaclavlegat** [comment]
Fixed 1. and 2.
