### ISSUE TITLE
'Sync Required' Dot Always Appears

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#51]
The little red dot indicating that a sync is required is always showing on my device. When first logging in and when offline changes are made. Syncing appears to be working correctly, as offline changes are being reflected in the web db, and the timestamp is updating, but the dot remains.

![image](https://user-images.githubusercontent.com/31128624/70242756-a8dcb000-1771-11ea-9231-7bde7fb1bca7.png)

**Comment by simon-krucinin-applifting** [comment]
Seems to happen only in certain conditions. Can't reproduce it on Samsung Galaxy S9.

**Comment by Happs80** [comment]
Ok same issue on Pixel 3. Android 10.

Open. Syncs ok. (Though takes v long time). 

And then make one assignment offline. Come back online and sync and sync works, but dot and text remain.

**Comment by PetrKubes97** [comment]
I unfortunately could not reproduce this error. Would be possilbe to post screenshots with opened sync dialog and copy of developer logs? (settings -> show developer logs) The only way I can see this happening is because of some faulty upload, but that way, a toast message should indicate that it was not successful.

**Comment by PetrKubes97** [comment]
@Happs80 or @simon-krucinin-applifting

**Comment by Happs80** [comment]
Please see here.

![Screenshot_20191207-201502](https://user-images.githubusercontent.com/31128624/70379554-5f858f80-192e-11ea-8949-a5364bdd15b0.jpg)


Android SDK: 28 (9)
0.7.0
06-12 14:38:50.06:Sync finished successfully
06-12 14:38:50.08:Worker state: SUCCEEDED
06-12 16:22:14.37:Started Sync
06-12 16:22:14.85:Worker state: RUNNING
06-12 16:22:14.86:Worker state: SUCCEEDED
06-12 16:22:15.93:Sync finished successfully
06-12 16:22:15.95:Worker state: SUCCEEDED
06-12 16:32:41.23:Started Sync
06-12 16:32:43.41:Sync finished successfully
06-12 16:35:12.06:Worker state: ENQUEUED
06-12 16:35:12.08:Worker state: SUCCEEDED
06-12 16:35:12.08:Worker state: ENQUEUED
06-12 16:35:15.20:Started Sync
06-12 16:35:17.72:Sync finished successfully
07-12 20:13:57.44:Started Sync
07-12 20:13:57.91:Worker state: SUCCEEDED
07-12 20:13:57.91:Worker state: RUNNING
07-12 20:13:57.92:Worker state: SUCCEEDED
07-12 20:13:59.53:Sync finished successfully
07-12 20:13:59.55:Worker state: SUCCEEDED
07-12 20:14:10.69:Started Sync
 ENQUEUED
07-12 20:14:10.70:Worker state: RUNNING
07-12 20:14:28.35:Sync finished successfully
07-12 20:14:28.38:Worker state: SUCCEEDED
07-12 20:14:43.34:Worker state: ENQUEUED
07-12 20:14:43.35:Worker state: RUNNING
07-12 20:14:43.36:Started Sync
07-12 20:15:01.24:Sync finished successfully
07-12 20:15:01.26:Worker state: SUCCEEDED

**Comment by Happs80** [comment]
Confirmed fixed ver 0.9

**Comment by simon-krucinin-applifting** [comment]
Fixed? 👀 Note to myself: verify on LG.

**Comment by simon-krucinin-applifting** [comment]
Tried on 2 different phones - LG G3 and Samsung Galaxy S9. Three new issues were found. One makes it impossible to retest this:

When a local change is made (a QR voucher assigned), no dot icon appears and the sync dialog says "No pending changes". On another phone it worked fine. This is very unreliable.
