### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#52]
Please, add Arabic translation to the app with following texts.

[countries.xlsx](https://github.com/Applifting/Humansis/files/3932582/countries.xlsx)
[string.xlsx](https://github.com/Applifting/Humansis/files/3932583/string.xlsx)

**Comment by PetrKubes97** [comment]
Implemented, but needs to checked by someone who speaks arabic, as the translator did not use placeholders and sometimes just translated the name of the string instead, which unfortunately does not make sense.
