### ISSUE TITLE
App Not Syncing Some Items - 403 Error

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#54]
Project manager rights. Other items sync successfully. Ver 0.7. Samsung c7. Android 8.0.

![image](https://user-images.githubusercontent.com/31128624/70570700-ae386100-1b9c-11ea-91db-1ae09d8146ca.png)

**Comment by simon-krucinin-applifting** [comment]
It turns out that backend invalidates the login session after all after some time. So we need to present a login screen with the user name locked where the password needs to be typed in again. With no option to log out or reset the app at that point. Then the data sync should be restarted.

**Comment by Happs80** [comment]
Still occurring, just at different stage it seems.

[20200113_153146.zip](https://github.com/Applifting/Humansis/files/4053897/20200113_153146.zip)

**Comment by Happs80** [comment]
Fixed.
