### ISSUE TITLE
Empty list of projects after first login

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#57]
When I install the app, log in for the first time with the demo account, the data is downloaded automatically (message "Nothing to display" disappears), but the list is empty -- no items displayed and I'm staring at an empty screen. Projects appear only after I leave the screen (e.g. to settings) and come back.

**Comment by vaclavlegat** [comment]
There was a timing problem between downloading X loading from DB.

**Comment by simon-krucinin-applifting** [comment]
Could be a fix for #51 potentially
