### ISSUE TITLE
QR codes marked as Used

### ISSUE THREAD

**Issue by simon-krucinin-applifting** [Applifting/Humansis#58]
Somehow, after a failed data sync, for a QR code distribution it happened that many codes were not marked Distributed, but Used instead. Only 4% actually succeeded. There could be another mistake that caused this earlier; it could have been a server issue. We need to check the app if we ever set the Used status and under what conditions.

**Comment by vaclavlegat** [comment]
We do not modify this property on our side. When we upload changes for QR code distribution, we call endpoint `booklets/assign/{beneficiaryId}/{distributionId}`, in request body we send only booklet QR code.

**Comment by simon-krucinin-applifting** [comment]
Thank you! The issue is not related to the app.
