### ISSUE TITLE
Syncing in Latest Version Not Working

### ISSUE THREAD

**Issue by Happs80** [Applifting/Humansis#62]
Sync Data button doesn't appear to do anything.

![image](https://user-images.githubusercontent.com/31128624/71654722-577f0b00-2d87-11ea-9232-f92e4d03f724.png)

![image](https://user-images.githubusercontent.com/31128624/71654797-ba70a200-2d87-11ea-93ab-c0d11bb7dd6b.png)

**Comment by Happs80** [comment]
Cannot replicate.

**Comment by simon-krucinin-applifting** [comment]
Worked after closing the app and trying again.

**Comment by simon-krucinin-applifting** [comment]
Tested on several devices by leaving changes for more than 24h before syncing. Worked fine. This looks like a rare glitch.
